### PR TITLE
Node needed 'use strict' statement

### PR DESCRIPTION
**Pull request by jlinc-victor**
Thanks for this library - works great, very useful! 

In order to make it work in Node (v4.2.4) I had to add a 'use strict' statement to the top of lib/main.js, otherwise I was getting this error message when I tried to require it: "SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode".

While I was at it, I added semicolons to the line endings so JSHINT would stop complaining.

### CODE REVIEW

**Comment by diracdeltas** [comment]
Thanks for pointing this out! I realized that I forgot to set the linter as Standard (http://standardjs.com/) in `package.json`, which by default does not require semicolons like jshint does. For style consistency, please open this PR without the semicolons. 

If you do `npm run lint` to lint with Standard, it should not throw any complaints.

**Comment by jlinc-victor** [comment]
Yes, after I submitted it I thought I should have left the semicolons out. Then somehow I seem to have gotten out of sync with your master. Here's the latest from your master with just 'use strict' added at the top. Sorry for the mess -- just throw the pull request away and add it yourself if it's cleaner.

**Comment by diracdeltas** [comment]
lgtm! could you please run `git rebase -i` to squash these 3 commits into a single commit?

**Comment by jlinc-victor** [comment]
yan <notifications@github.com> wrote:
> lgtm! could you please run git rebase -i to squash these 3 commits into a single commit?

This seems to have exceeded my very poor git abilities, so I just killed the pull request a created another with one simple commit.
Hope that serves.

Cheers,
=vg

**Pull request closed without merging**
