### PR TITLE
Add Codespell action

### PR DESCRIPTION
**Pull request by peternewman**

### CODE REVIEW

**Comment by peternewman** [comment]
This has found a number of errors:
https://github.com/peternewman/niceware/actions/runs/197104926

But only in browser/niceware.js not lib/wordlist.js, your build doesn't seem to use wordlist though (from what I can see):
https://github.com/diracdeltas/niceware/blob/2cf54bdf9dae702b63b82d3a5bac8453eb0cceae/package.json#L34

**Comment by diracdeltas** [comment]
thanks for doing this! unfortunately all of these spelling errors (except 'keypair' which i contend is a real word) were generated by [browserify](http://browserify.org/), a tool which this repo uses to autogenerate browser code. as such, i can't fix the spelling errors without them being overriden every time a new build is generated.

**Comment by peternewman** [comment]
> thanks for doing this! unfortunately all of these spelling errors (except 'keypair' which i contend is a real word) were generated by [browserify](http://browserify.org/), a tool which this repo uses to autogenerate browser code. as such, i can't fix the spelling errors without them being overriden every time a new build is generated.

:facepalm: oops @diracdeltas , I need to work out what I first spotted and unpick it (edit, see below). I've opened an upstream issue to fix browserify ( https://github.com/browserify/browserify/pull/1975 ), although those typos don't exist in it (although I found a lot of other upstream in https://github.com/feross/buffer/pull/269 and https://github.com/defunctzombie/node-process/pull/89 ). In the meantime, I've just skipped that file anyway. See for example:
https://github.com/peternewman/niceware/actions/runs/198897858

Incidentally something like this looks like it could probably minify that generated output at the bottom I think:
https://www.npmjs.com/package/tinyify

> (except 'keypair' which i contend is a real word)

Do you have some source or links for that? A Google finds AWS, Java and Wikipedia all referring to two words. Outscale (whatever that is) is one of the few things I could find which uses one word. We could also skip it though like other words.

https://github.com/codespell-project/codespell/pull/1613 was what started me at this, although after a bit more digging it seems to be a rare but real word so I've left it for now.

**Comment by peternewman** [comment]
@diracdeltas are you interested in merging it now it only checks your actual code?

As I mentioned, if you've got some detail on keypair, it would be great to correct the dictionary, or if it's just personal preference it's also trivial to skip in your repo check?

**Comment by diracdeltas** [comment]
> As I mentioned, if you've got some detail on keypair, it would be great to correct the dictionary, or if it's just personal preference it's also trivial to skip in your repo check?

it does seem used less frequently than i thought so i'm happy to use the more common two-word spelling. i will merge this and then fix it. 

thanks for the PR!

**Comment by peternewman** [comment]
> > As I mentioned, if you've got some detail on keypair, it would be great to correct the dictionary, or if it's just personal preference it's also trivial to skip in your repo check?
> 
> it does seem used less frequently than i thought so i'm happy to use the more common two-word spelling. i will merge this and then fix it.

Great, we'll leave our dictionary as-is then.

> thanks for the PR!

No worries.

**Pull request merged**
